apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elsonpulikkan/estore-amazon.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
