apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elsonpulikkan96/EKS-AWS-Terraform-Module-Project.git
    targetRevision: HEAD
    path: deployment
    directory:
      include: 'namespace.yml'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
